apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    url: mysql:3306
    database: infra_monitor
    user: monitor_user
    secureJsonData:
      password: monitor_pass123
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      timezone: Asia/Seoul
    isDefault: true
    editable: true
