# Generated by Django 5.0.4 on 2026-04-21 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50)),
                ('threshold', models.FloatField()),
                ('actual_value', models.FloatField()),
                ('message', models.TextField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alert_history',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '사용자'), ('assistant', 'AI')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default='zorin-vm', max_length=100)),
                ('cpu_usage', models.FloatField()),
                ('mem_total', models.BigIntegerField()),
                ('mem_used', models.BigIntegerField()),
                ('mem_percent', models.FloatField()),
                ('disk_total', models.BigIntegerField()),
                ('disk_used', models.BigIntegerField()),
                ('disk_percent', models.FloatField()),
                ('net_bytes_sent', models.BigIntegerField(default=0)),
                ('net_bytes_recv', models.BigIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_metrics',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='AiAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', '정보'), ('warning', '경고'), ('critical', '위험')], default='info', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('analysis', models.TextField()),
                ('suggestion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.systemmetric')),
            ],
            options={
                'db_table': 'ai_analysis',
                'ordering': ['-created_at'],
            },
        ),
    ]
